export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  mathbankRosterToken: process.env.MATHBANK_ROSTER_TOKEN ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY ?? "",
  vapidPrivateKey: process.env.VAPID_PRIVATE_KEY ?? "",
  vapidSubject: process.env.VAPID_SUBJECT ?? "mailto:admin@haemil.local",
  adminEmail: process.env.ADMIN_EMAIL ?? "",
  adminPasswordHash: process.env.ADMIN_PASSWORD_HASH ?? "",
  adminName: process.env.ADMIN_NAME ?? "해밀 관리자",
  uploadDir: process.env.UPLOAD_DIR ?? "",
  solapiApiKey: process.env.SOLAPI_API_KEY ?? "",
  solapiApiSecret: process.env.SOLAPI_API_SECRET ?? "",
  solapiSenderNumber: process.env.SOLAPI_SENDER_NUMBER ?? "",
  solapiKakaoPfId: process.env.SOLAPI_KAKAO_PF_ID ?? "",
  solapiRemainingOneTemplateId:
    process.env.SOLAPI_REMAINING_ONE_TEMPLATE_ID ?? "",
  solapiPaymentConfirmedTemplateId:
    process.env.SOLAPI_PAYMENT_CONFIRMED_TEMPLATE_ID ?? "",
};
