import type { RewardOrderInput } from "./avatarRewards";
export const avatarThemes = [
  "중세유럽",
  "조선시대",
  "스쿨룩",
  "KPOP/무대스타",
  "스포츠스타",
  "판타지",
  "미래",
] as const;
export type AvatarTheme = (typeof avatarThemes)[number];
export const avatarThemeDirections: Record<AvatarTheme, string> = {
  중세유럽:
    "Grounded historical costume drama. Use period textiles, tailoring, leather goods, stone streets, castles, markets, ports and wooden sailing ships. No magic, glowing objects, spell effects, fantasy creatures, floating architecture or steampunk machinery.",
  조선시대:
    "Grounded Joseon-era historical drama. Respect traditional clothing, architecture, crafts and daily life. No magic, supernatural glow, mythical creatures, floating structures or modern objects.",
  스쿨룩:
    "Contemporary real-world Korean school life and youth editorial styling. Use believable classrooms, clubs, libraries, studios and sports grounds. No magic, fantasy creatures, impossible environments or sci-fi gadgets.",
  "KPOP/무대스타":
    "A believable KPOP music-show, concert, showcase or awards-stage production. Use real stage lighting, microphones, cameras, LED sets and performance clothing. Keep the student age-appropriate. No magic or supernatural effects.",
  스포츠스타:
    "A believable competitive sports scene with correct equipment, venue, body mechanics and practical uniforms. Keep natural student proportions and avoid exaggerated muscles. No superpowers, energy auras or impossible action.",
  판타지:
    "Premium imaginative fantasy is welcome. Keep the selected concept coherent, age-appropriate and visually elegant.",
  미래: "Plausible near-future science and engineering developed from real technology. Use functional equipment, research facilities, transport, robotics and displays. No magic, supernatural creatures, anti-gravity fantasy or impossible physics.",
};
type Preset = Omit<
  RewardOrderInput,
  "mode" | "accessories" | "selectedParts"
> & { name: string; accessory: string };
const make = (theme: string, i: number, values: string[]): Preset => ({
  name: `${theme} ${i + 1} · ${values[0]}`,
  top: values[1],
  bottom: values[2],
  shoes: values[3],
  hair: values[4],
  background: values[5],
  accessory: values[6],
  pet: values[7],
  pose: values[8],
  extra: values[9],
});
const rows: Record<AvatarTheme, string[][]> = {
  중세유럽: [
    [
      "항구의 젊은 항해사",
      "아이보리 리넨 셔츠와 짙은 갈색 조끼",
      "여유 있는 짙은 갈색 항해 바지",
      "낡은 갈색 가죽 부츠",
      "바닷바람에 자연스럽게 흐트러진 머리",
      "돛과 밧줄이 보이는 목조 범선 갑판",
      "황동 망원경과 가죽 허리 파우치",
      "갑판 난간에 앉은 갈매기",
      "한쪽 무릎을 세우고 망원경으로 수평선 살피기",
      "맑은 낮의 바다와 생활감 있는 대항해 시대 분위기",
    ],
    [
      "항구 도시의 해적풍 탐험가",
      "풍성한 흰 셔츠와 검정 코르셋형 조끼",
      "겹쳐진 짙은색 스커트 또는 활동적인 항해 바지",
      "갈색 가죽 버클 부츠",
      "삼각모자 아래 자연스럽게 땋은 머리",
      "검은 깃발과 돛대가 보이는 항구의 범선",
      "넓은 가죽 벨트와 지도 파우치",
      "밧줄 위에 앉은 앵무새",
      "갑판 위에서 자신감 있게 수평선을 바라보기",
      "마법 없이 거칠고 자유로운 역사 모험극 분위기",
    ],
    [
      "성벽 장터의 견습 상인",
      "크림색 퍼프소매 블라우스와 올리브색 레이스업 보디스",
      "벽돌색 발목 길이 주름치마 또는 단정한 리넨 바지",
      "튼튼한 갈색 가죽 단화",
      "리본으로 묶은 한쪽 땋은 머리",
      "햇살 드는 석조 골목의 붐비는 중세 장터",
      "동전 주머니와 작은 천 가방",
      "발치에서 쉬는 시장 고양이",
      "장바구니를 들고 장터를 씩씩하게 걷기",
      "흙길과 목재 가판대가 살아 있는 소박한 시대극 분위기",
    ],
    [
      "성의 젊은 귀족",
      "짙은 청록 벨벳 예복과 은색 자수 장식",
      "품위 있는 풍성한 궁정 스커트 또는 무릎 길이 브리치",
      "장식 버클이 달린 검정 궁정화",
      "진주 장식으로 단정하게 올린 머리",
      "촛대와 조각 거울이 놓인 르네상스풍 성의 응접실",
      "작은 부채 또는 봉인된 편지",
      "창가에 얌전히 앉은 애완견",
      "예복의 실루엣이 잘 보이도록 우아하게 서기",
      "무겁고 고급스러운 직물과 절제된 왕실 초상화 분위기",
    ],
    [
      "왕실 축제의 공주와 왕자",
      "레이스와 리본이 겹쳐진 파스텔 궁정 예복",
      "풍성한 종형 드레스 스커트 또는 자수 장식 브리치",
      "새틴 리본 궁정화",
      "잔잔한 컬과 리본으로 장식한 궁정식 머리",
      "대리석 기둥과 긴 커튼이 있는 밝은 왕궁 홀",
      "작은 꽃다발과 섬세한 장갑",
      "쿠션 옆에 앉은 작은 흰 토끼",
      "치맛자락이나 코트 자락을 살짝 잡고 정중히 인사하기",
      "분홍과 아이보리 레이스가 돋보이는 동화 같은 역사 의상극 분위기",
    ],
  ],
  조선시대: [
    [
      "서당의 젊은 학자",
      "은은한 옥색 도포와 흰 저고리",
      "짙은 남색 한복 바지",
      "흰 버선과 검정 태사혜",
      "망건이나 댕기로 단정히 묶은 머리",
      "책장과 문방사우가 놓인 낮의 서당",
      "한지 책과 붓통",
      "마루 아래 쉬고 있는 고양이",
      "책을 펼쳐 읽으며 잔잔하게 미소 짓기",
      "한지와 나무 질감이 살아 있는 차분한 조선 생활상",
    ],
    [
      "궁궐의 어린 화원",
      "모란 자수 연분홍 저고리",
      "짙은 남색 한복 치마 또는 바지",
      "꽃 자수 비단신",
      "댕기나 관모와 어울리는 단정한 머리",
      "연못과 정자가 보이는 햇살 좋은 궁궐 후원",
      "붓과 전통 화첩",
      "연못가를 걷는 실제 학",
      "화첩에 모란을 관찰해 그리기",
      "고증을 존중한 자연광의 궁중 기록화 분위기",
    ],
    [
      "비밀 암행 기록관",
      "검푸른 철릭과 답호",
      "활동적인 전통 바지",
      "구름 문양 목화",
      "갓과 어울리는 머리",
      "비 갠 한양 등불 골목",
      "마패 모양 수첩",
      "기와담 위에 앉은 까치",
      "수첩의 단서 확인하기",
      "위협적 무기 없는 영리한 모험",
    ],
    [
      "궁중 연회의 악사",
      "붉은색 전통 악사복",
      "검정 전통 바지 또는 긴 치마",
      "금박 비단신",
      "관모와 어울리는 머리",
      "등불이 켜진 궁궐 연회 마당",
      "작은 장구",
      "악기 곁에 놓인 북채 주머니",
      "장구를 힘차게 연주하기",
      "붉은 단청과 따뜻한 등불이 어우러진 실제 공연 분위기",
    ],
    [
      "바람의 연 장인",
      "색동 연청색 저고리",
      "편안한 회색 한복 바지",
      "구름색 전통 신발",
      "댕기로 묶은 머리",
      "억새 들판과 성곽",
      "나무 실패와 여분의 연실",
      "들판을 함께 달리는 삽살개",
      "나비연 실을 잡고 달리기",
      "민화 같은 생동감",
    ],
  ],
  스쿨룩: [
    [
      "방과 후 천문부",
      "네이비 바시티 재킷과 흰 티셔츠",
      "와이드 카고 팬츠",
      "흰색 캔버스 운동화",
      "자연스러운 쉼표머리",
      "노을 진 학교 옥상 천문대",
      "천문 관측 노트와 학생증",
      "망원경 옆에 놓인 별자리 책",
      "망원경을 조절하며 웃기",
      "세련된 동아리 화보",
    ],
    [
      "비 오는 날 도서위원",
      "크림 가디건과 셔츠",
      "잔체크 플리츠 하의",
      "단정한 흰색 스니커즈",
      "자연스럽게 묶은 머리",
      "비 내리는 학교 도서관",
      "책갈피 브로치",
      "책상 위 머그컵과 접힌 우산",
      "책을 안고 창밖 보기",
      "따뜻한 실내와 푸른 빗빛",
    ],
    [
      "컬러풀 미술부",
      "물감 자국이 살짝 묻은 후드 집업",
      "데님 와이드 팬츠",
      "알록달록 흰 운동화",
      "색색 실핀으로 정돈한 머리",
      "캔버스와 석고상이 놓인 실제 미술실",
      "팔레트 미니백",
      "붓이 꽂힌 물통",
      "큰 캔버스에 무지개를 그리기",
      "프리미엄 청춘 화보",
    ],
    [
      "점심시간 방송부 DJ",
      "은색 라인 교복 재킷",
      "단정한 차콜 하의",
      "메탈 로퍼",
      "헤드폰과 자연스러운 머리",
      "마이크와 믹서가 놓인 학교 방송실",
      "레트로 마이크 핀",
      "대본과 방송 시간표",
      "헤드폰을 잡고 방송하기",
      "창문으로 들어오는 낮빛과 또렷한 얼굴",
    ],
    [
      "가을 학교 체육대회",
      "하늘색 스포티 재킷과 팀 조끼",
      "편안한 트랙 팬츠",
      "가벼운 러닝화",
      "달리기 편하게 묶은 머리",
      "만국기와 응원석이 보이는 학교 운동장",
      "팀 색상 응원 배지",
      "출발선 옆 릴레이 배턴",
      "결승선을 향해 뛰기",
      "역동적이고 또렷한 전신",
    ],
  ],
  "KPOP/무대스타": [
    [
      "뮤직쇼 센터",
      "크롭되지 않은 메탈릭 포인트 무대 재킷",
      "블랙 와이드 팬츠 또는 단정한 플리츠 스커트",
      "화이트 하이탑 퍼포먼스 슈즈",
      "무대 조명에 선명한 자연스러운 스타일링",
      "LED 패널과 스포트라이트가 있는 음악방송 무대",
      "헤드셋 마이크",
      "무대 바닥의 인이어 모니터 케이스",
      "카메라를 바라보며 포인트 안무 동작 하기",
      "실제 KPOP 음악방송처럼 세련되고 에너지 넘치는 연출",
    ],
    [
      "청량한 여름 컴백",
      "파스텔 셔츠와 가벼운 데님 레이어드",
      "밝은색 데님 팬츠 또는 무릎 아래 플리츠 스커트",
      "컬러 포인트 스니커즈",
      "산뜻하고 자연스러운 컴백 헤어",
      "하늘색 세트와 야자수 소품이 있는 밝은 쇼케이스 무대",
      "무선 핸드 마이크",
      "무대 한쪽의 컬러 스피커",
      "관객에게 손을 흔들며 경쾌하게 걷기",
      "과장된 판타지 효과 없는 청량한 아이돌 무대 화보",
    ],
    [
      "강렬한 댄스 퍼포머",
      "레드 포인트 블랙 테크웨어 재킷",
      "움직임이 편한 블랙 카고 팬츠",
      "검정 댄스 스니커즈",
      "단단히 고정한 퍼포먼스 헤어",
      "붉은 조명과 철제 트러스가 보이는 콘서트 무대",
      "헤드셋 마이크와 인이어",
      "바닥에 놓인 무대 타월",
      "낮은 중심의 강한 댄스 포즈",
      "실제 콘서트 조명과 땀의 질감이 느껴지는 긴장감",
    ],
    [
      "어쿠스틱 보컬리스트",
      "아이보리 셔츠와 부드러운 니트 베스트",
      "차분한 브라운 슬랙스 또는 롱스커트",
      "클래식 로퍼",
      "꾸민 듯 자연스러운 웨이브 헤어",
      "밴드 악기와 따뜻한 전구가 놓인 소극장 무대",
      "스탠드 마이크",
      "옆 의자에 놓인 어쿠스틱 기타",
      "마이크를 두 손으로 잡고 노래하기",
      "관객과 가까이 호흡하는 따뜻한 라이브 공연 분위기",
    ],
    [
      "연말 시상식 스타",
      "벨벳과 새틴을 사용한 단정한 시상식 의상",
      "격식 있는 와이드 팬츠 또는 발목 길이 드레스 스커트",
      "광택을 절제한 검정 무대화",
      "레드카펫에 어울리는 정교한 헤어",
      "금빛 조명과 계단이 있는 연말 시상식 무대",
      "트로피와 무선 마이크",
      "무대 옆 꽃다발",
      "트로피를 들고 객석에 감사 인사하기",
      "학생 나이를 유지한 품격 있는 시상식 주인공 연출",
    ],
  ],
  스포츠스타: [
    [
      "축구 결승전 에이스",
      "번호가 없는 깔끔한 팀 컬러 축구 유니폼",
      "축구 쇼츠와 긴 양말",
      "잔디용 축구화",
      "경기에 방해되지 않게 정돈한 머리",
      "관중석이 가득 찬 천연잔디 축구장",
      "축구공과 주장 완장",
      "골대 옆 물병",
      "공을 발밑에 두고 킥 직전 자세 잡기",
      "실제 스포츠 중계의 선명한 낮 경기 분위기",
    ],
    [
      "농구 코트의 플레이메이커",
      "로고 없는 민소매 농구 저지와 이너 셔츠",
      "무릎 길이 농구 쇼츠",
      "발목을 지지하는 농구화",
      "땀에도 흐트러지지 않는 운동 헤어",
      "조명이 밝은 실내 농구 경기장",
      "농구공과 손목 밴드",
      "벤치 옆 스포츠 타월",
      "드리블하며 수비 방향을 살피기",
      "속도와 집중력이 느껴지는 실제 경기 장면",
    ],
    [
      "배드민턴 국가대표 꿈나무",
      "화이트와 네이비 기능성 경기 셔츠",
      "활동적인 스포츠 쇼츠 또는 스커트",
      "논마킹 코트화",
      "단정히 묶은 경기용 머리",
      "라인이 또렷한 실내 배드민턴 코트",
      "라켓과 셔틀콕",
      "코트 옆 라켓 가방",
      "높은 셔틀콕을 향해 스매시 준비하기",
      "빠른 셔터로 포착한 실제 대회 사진 같은 역동성",
    ],
    [
      "육상 트랙의 스프린터",
      "통기성 좋은 팀 컬러 러닝 싱글렛",
      "몸에 맞는 러닝 쇼츠 또는 레깅스",
      "트랙용 스파이크화",
      "공기 저항을 줄이도록 정돈한 머리",
      "관중석과 전광판이 보이는 붉은 육상 트랙",
      "출발 번호표 없는 손목 스톱워치",
      "출발선 옆 스타팅 블록",
      "스타팅 블록에서 출발 신호를 기다리기",
      "근육을 과장하지 않고 폭발적인 출발 직전의 집중감",
    ],
    [
      "빙상장의 피겨 스타",
      "학생다운 단정한 장식의 긴팔 피겨 의상",
      "움직임을 살리는 스케이팅 팬츠 또는 무릎 길이 스커트",
      "흰색 또는 검정 피겨 스케이트",
      "회전에 안정적인 깔끔한 헤어",
      "관중석과 심판석이 보이는 실제 아이스링크",
      "얇은 연습 장갑",
      "링크 가장자리의 스케이트 커버",
      "빙판 위에서 균형 잡힌 스파이럴 자세",
      "얼음 반사와 경기장 조명을 사실적으로 살린 대회 분위기",
    ],
  ],
  판타지: [
    [
      "별빛 용의 친구",
      "별자리 자정빛 후드티",
      "은하수 검정 와이드 팬츠",
      "별빛 운동화",
      "오로라 끝 검정 머리",
      "고래 구름 하늘 기차역",
      "행성 목걸이",
      "별빛 아기 용",
      "작은 달을 받치고 미소 짓기",
      "나비 모양 그림자",
    ],
    [
      "공중 도서관 사서",
      "오로라 안감 구름 재킷",
      "종이별 카고 바지",
      "투명 우주 하이탑",
      "은하빛 별핀 머리",
      "별자리 공중 도서관",
      "홀로그램 시계",
      "우주 고양이",
      "펫과 하이파이브하기",
      "민트 보라 종이별",
    ],
    [
      "해저 정원 여행자",
      "고래 남색 맨투맨",
      "물결 데님 팬츠",
      "민트 스니커즈",
      "청록빛 웨이브",
      "해파리 해저 정원",
      "구름 유리 귀걸이",
      "솜사탕 여우",
      "손끝으로 별자리 그리기",
      "따뜻한 동화책 빛",
    ],
    [
      "달빛 우편배달부",
      "햇살 주머니 바람막이",
      "노을 주름 하의",
      "달빛 구름 부츠",
      "노을빛 한 가닥 머리",
      "구름 우편함 산책길",
      "별가루 미니 가방",
      "작은 하늘 고래",
      "종이비행기를 날리기",
      "눈동자에 별빛",
    ],
    [
      "시간 정원 수호자",
      "시곗바늘 청록 코트",
      "톱니꽃 짙은 하의",
      "시간 모래 투명 부츠",
      "은빛 꽃잎 머리",
      "계절이 공존하는 시간 정원",
      "수정 회중시계",
      "초침 꼬리 작은 사자",
      "시간을 손으로 되감기",
      "청록과 금빛 고리",
    ],
  ],
  미래: [
    [
      "화성 연구기지 탐사생",
      "흰색 경량 탐사 재킷",
      "먼지 차단 기능성 팬츠",
      "접지력이 높은 탐사 부츠",
      "헬멧에 편하게 들어가는 단정한 머리",
      "창밖으로 화성 지표가 보이는 현실적인 연구기지",
      "태블릿 지도와 통신 헤드셋",
      "바퀴형 소형 탐사 로버",
      "로버 옆에서 지질 표본을 기록하기",
      "현재 우주개발 기술을 발전시킨 현실적 근미래",
    ],
    [
      "도시형 온실 생물학자",
      "세이지색 연구 재킷과 기능성 셔츠",
      "수납 포켓이 있는 연구용 팬츠",
      "미끄럼 방지 작업화",
      "위생적으로 묶은 자연스러운 머리",
      "자동 관수 장치가 설치된 고층 건물 온실",
      "식물 측정 센서와 태블릿",
      "작물 운반용 소형 카트 로봇",
      "잎의 생육 데이터를 태블릿에 기록하기",
      "실현 가능한 농업기술 중심의 깨끗한 근미래",
    ],
    [
      "초고속 열차 기관사",
      "노선 색상 포인트가 있는 기능성 제복",
      "단정한 차콜 작업 바지",
      "안전화형 검정 부츠",
      "제복 모자와 어울리는 단정한 머리",
      "대형 전면창과 실제 계기판이 있는 고속열차 운전실",
      "전자 운행표와 무전기",
      "점검용 소형 드론",
      "계기판을 확인하며 출발 준비하기",
      "자동운행과 인간 관제가 공존하는 현실적 교통 미래",
    ],
    [
      "미래 도시 미디어 DJ",
      "음향 반응 센서가 달린 오버핏 재킷",
      "실버 포인트 와이드 팬츠",
      "편안한 퍼포먼스 하이탑",
      "헤드셋 자연스러운 머리",
      "대형 투명 디스플레이가 있는 도심 방송 스튜디오",
      "웨어러블 믹서 컨트롤러",
      "카메라를 이동시키는 촬영 드론",
      "실물 믹서와 터치 디스플레이를 조작하기",
      "실제 방송 장비를 발전시킨 세련된 근미래 무대",
    ],
    [
      "도심 드론 배송 관제사",
      "반사 라인이 있는 배송 관제 재킷",
      "수납형 카고 팬츠",
      "충격 흡수 작업 운동화",
      "헤드셋과 어울리는 실용적인 머리",
      "배송 드론이 이착륙하는 고층 물류센터",
      "배송 태블릿과 바코드 스캐너",
      "잠금형 소형 배송 드론",
      "도착한 소포를 스캔하고 드론 경로 확인하기",
      "현실적인 자동 물류 시스템과 맑은 미래 도시 풍경",
    ],
  ],
};
export const avatarThemePresets = Object.fromEntries(
  avatarThemes.map(theme => [
    theme,
    rows[theme].map((v, i) => make(theme, i, v)),
  ])
) as Record<AvatarTheme, Preset[]>;
export function chooseThemePreset(theme: AvatarTheme, random = Math.random) {
  return avatarThemePresets[theme][Math.min(4, Math.floor(random() * 5))];
}
export function avatarThemePrompt(theme: AvatarTheme) {
  return `HAEMIL SPECIAL AVATAR · ${theme}\nCreate TWO clearly different premium semi-webtoon full-body portraits from the same Master Avatar. Both results must preserve recognizable identity and age, but must differ at first glance in pose, body direction, camera angle, expression, lighting, background composition and companion placement. Never return near-duplicates, mirrored copies or a simple color variation. Head and shoes fully visible, clear face for circular crop, age-appropriate styling, no text, logo, watermark or collage.\n\nTHEME DIRECTION\n${avatarThemeDirections[theme]}\n\nChoose one coherent concept from these five ${theme} presets:\n${avatarThemePresets[theme].map((x, i) => `${i + 1}. ${x.name}: ${x.top}; ${x.bottom}; ${x.shoes}; ${x.hair}; ${x.background}; ${x.accessory}; ${x.pet}; ${x.pose}; ${x.extra}`).join("\n")}`;
}
